# Generated by Django 5.2.12 on 2026-03-23 00:00

from django.db import migrations, models


def deduplicate_user_profile_nicknames(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    seen = set()

    for profile in UserProfile.objects.select_related("user").order_by("user_id"):
        base = (profile.nickname or "").strip()
        if not base:
            email_prefix = ""
            if getattr(profile, "user", None) and getattr(profile.user, "email", ""):
                email_prefix = profile.user.email.split("@")[0].strip()
            base = email_prefix or "user"

        candidate = base[:100]
        suffix = 2

        while candidate in seen:
            suffix_text = str(suffix)
            truncated_base = base[: max(1, 100 - len(suffix_text))]
            candidate = f"{truncated_base}{suffix_text}"
            suffix += 1

        if candidate != profile.nickname:
            profile.nickname = candidate
            profile.save(update_fields=["nickname"])

        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userpreference_userusedproduct"),
    ]

    operations = [
        migrations.RunPython(deduplicate_user_profile_nicknames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
