# Generated by Django 5.2.12 on 2026-03-17 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('cat', '고양이'), ('dog', '강아지')], max_length=5)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', '수컷'), ('female', '암컷')], max_length=10)),
                ('age_years', models.IntegerField(default=0)),
                ('age_months', models.IntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neutered', models.BooleanField(blank=True, null=True)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(max_length=20)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pet_allergy',
            },
        ),
        migrations.CreateModel(
            name='PetFoodPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_type', models.CharField(choices=[('dry', '건식'), ('wet_can', '습식캔'), ('wet_pouch', '습식파우치'), ('freeze_dried', '동결건조'), ('raw', '생식')], max_length=20)),
            ],
            options={
                'db_table': 'pet_food_preference',
            },
        ),
        migrations.CreateModel(
            name='PetHealthConcern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concern', models.CharField(choices=[('skin', '피부'), ('joint', '관절'), ('digestion', '소화'), ('weight', '체중'), ('urinary', '요로'), ('eye', '눈물'), ('hairball', '헤어볼'), ('dental', '치아'), ('immunity', '면역')], max_length=20)),
            ],
            options={
                'db_table': 'pet_health_concern',
            },
        ),
        migrations.CreateModel(
            name='PetUsedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pet_used_product',
            },
        ),
    ]
