# Generated by Django 5.2.12 on 2026-03-17 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petallergy',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petfoodpreference',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='pethealthconcern',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_concerns', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petusedproduct',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petusedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by_pets', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='petallergy',
            unique_together={('pet', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='petfoodpreference',
            unique_together={('pet', 'food_type')},
        ),
        migrations.AlterUniqueTogether(
            name='pethealthconcern',
            unique_together={('pet', 'concern')},
        ),
        migrations.AlterUniqueTogether(
            name='petusedproduct',
            unique_together={('pet', 'product')},
        ),
    ]
