# Generated by Django 5.2.12 on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuturePetProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_species", models.CharField(blank=True, default="", max_length=20)),
                ("housing_type", models.CharField(blank=True, default="", max_length=20)),
                ("experience_level", models.CharField(blank=True, default="", max_length=20)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_pet_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "future_pet_profile",
            },
        ),
        migrations.AlterField(
            model_name="petfoodpreference",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("dry", "건식"),
                    ("wet_can", "습식"),
                    ("wet_pouch", "습식파우치"),
                    ("freeze_dried", "동결건조/에어드라이"),
                    ("raw", "혼합/자연식"),
                    ("soft", "소프트"),
                    ("cooked", "화식"),
                ],
                max_length=20,
            ),
        ),
    ]
