# Generated by Django 5.1 on 2026-03-16 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('goods_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('goods_name', models.TextField()),
                ('brand_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('thumbnail_url', models.TextField()),
                ('product_url', models.TextField()),
                ('soldout_yn', models.BooleanField(default=False)),
                ('popularity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trend_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('main_ingredients', models.JSONField(blank=True, null=True)),
                ('ingredient_composition', models.JSONField(blank=True, null=True)),
                ('nutrition_info', models.JSONField(blank=True, null=True)),
                ('ingredient_text_ocr', models.TextField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product',
                'indexes': [models.Index(fields=['brand_name'], name='product_brand_n_e9c6c7_idx'), models.Index(fields=['-popularity_score'], name='product_popular_d49b21_idx'), models.Index(fields=['-trend_score'], name='product_trend_s_47c0b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAdminConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('pinned', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_config', to='products.product')),
            ],
            options={
                'db_table': 'product_admin_config',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('관절', '관절'), ('피부', '피부'), ('소화', '소화'), ('체중', '체중'), ('요로', '요로'), ('눈물', '눈물'), ('헤어볼', '헤어볼'), ('치아', '치아'), ('면역', '면역')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='products.product')),
            ],
            options={
                'db_table': 'product_category_tag',
                'unique_together': {('product', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.TextField()),
                ('author_nickname', models.CharField(max_length=100)),
                ('written_at', models.DateField()),
                ('purchase_label', models.CharField(blank=True, choices=[('first', '첫 구매'), ('repeat', '재구매')], max_length=10, null=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', '긍정'), ('negative', '부정'), ('neutral', '중립')], max_length=10, null=True)),
                ('absa_result', models.JSONField(blank=True, null=True)),
                ('pet_age_months', models.IntegerField(blank=True, null=True)),
                ('pet_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pet_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'db_table': 'review',
                'indexes': [models.Index(fields=['product'], name='review_product_869586_idx'), models.Index(fields=['-written_at'], name='review_written_370c0f_idx')],
            },
        ),
    ]
