# Generated by Django 6.0.3 on 2026-03-24 03:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.extensions
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prefix',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prefix'], name='product_prefix_24e246_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_product_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_product_search_vector'),
        ),
    ]
