# Generated by Django 5.2.12 on 2026-04-01 01:09

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_local_db_schema_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guide_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guide_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='identity_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='identity_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
