services:
  fastapi:
    image: __FASTAPI_IMAGE__
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --workers 2
    env_file:
      - .env
    ports:
      - "80:8001"
    restart: unless-stopped
